### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by EIREXE** [manuelruder/artistic-videos#1]
I assume this is normal, but I'm reporting it in case it's a real issue, I'm using a GTX 780 in debian.

`eirexe@EIREXE-Debian:~/artistic-videos$ th artistic_video.lua -style_image starry_night.jpg -content_pattern frame_%04d.ppm -num_images 24 -gpu 0 -optimizer adam
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Style image size: 607 x 379	
Setting up temporal consistency.	
Setting up style layer  	2	:	relu1_1	
Setting up style layer  	7	:	relu2_1	
Setting up style layer  	12	:	relu3_1	
Setting up style layer  	21	:	relu4_1	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-7004/cutorch/lib/THC/generic/THCStorage.cu line=41 error=2 : out of memory
/home/eirexe/torch/install/bin/luajit: /home/eirexe/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 19 module of nn.Sequential:
/home/eirexe/torch/install/share/lua/5.1/nn/THNN.lua:109: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-7004/cutorch/lib/THC/generic/THCStorage.cu:41
stack traceback:
	[C]: in function 'v'
	/home/eirexe/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialConvolutionMM_updateOutput'
	...xe/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:111: in function <...xe/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:107>
	[C]: in function 'xpcall'
	/home/eirexe/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/eirexe/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./artistic_video_core.lua:229: in function 'buildNet'
	artistic_video.lua:102: in function 'main'
	artistic_video.lua:340: in main chunk
	[C]: in function 'dofile'
	...rexe/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405bd0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/eirexe/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/eirexe/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./artistic_video_core.lua:229: in function 'buildNet'
	artistic_video.lua:102: in function 'main'
	artistic_video.lua:340: in main chunk
	[C]: in function 'dofile'
	...rexe/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405bd0
`

**Comment by manuelruder** [comment]
This algorithm needs a lot of VRAM. You could try to downsample the video until it works. Memory usage scales linearly with video resolution. Maybe something like 300x200 might work with 3 GB VRAM.

jcjohnson suggested that using a different network might also reduce memory usage (see [neural-style#setup](https://github.com/jcjohnson/neural-style#setup)).

Then try something like (according to [here](https://github.com/jcjohnson/neural-style#usage)):
`th artistic_video.lua ... -model_file models/nin_imagenet_conv.caffemodel -proto_file models/train_val.prototxt -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 ...`

I haven't tried this myself yet, so you will enter new territory here.

**Comment by EIREXE** [comment]
Yeah I figured, I'll try that thanks

**Comment by manuelruder** [comment]
Another thing I forgot to mention: You could also try to use cuDNN. This reduces memory usage as well, but requires registration with NVIDIA. I have updated the description.

**Comment by linrio** [comment]
@EIREXE  Have you try manueruder's mathod @manuelruder  to reduce memory? I want to transfer higher piexl videos like 1k, 2K even 4k, however the size of my server's VRAM is 8GB (NV GTX 1070).
