### ISSUE TITLE
Error running line 84 of stylizeVideo.sh

### ISSUE THREAD

**Issue by slessie** [manuelruder/artistic-videos#11]
Got an error after computing the optical flow

Line 84 of stylizeVideo.sh which is 

`th artistic_video.lua \`

Any idea why?

Here is my terminal  output. 

zed@zed-desktop:~/artistic-videos$ sudo bash stylizeVideo.sh 'wingsuit/wing-%03d.png' 'styles/mountains.jpg'

Which backend do you want to use? For Nvidia GPU, use cudnn if available, otherwise nn. For non-Nvidia GPU, use clnn. Note: You have to have the given backend installed in order to use it. [nn] 
 > clnn

This algorithm needs a lot of memory.   For a resolution of 450x350 you'll need roughly 4GB VRAM.   VRAM usage increases linear with resolution.   Maximum recommended resolution with a Titan X 12GB: 960:540.   Please enter a resolution at which the video should be processed,   in the format w:h, or leave blank to use the original resolution 
 > 600:338
ffmpeg version N-80283-g84efdab Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 46.100 / 57. 46.100
  libavformat    57. 37.101 / 57. 37.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.101 /  6. 46.101
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, image2, from 'wingsuit/wing-%03d.png':
  Duration: 00:00:08.72, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 720x404 [SAR 254:255 DAR 3048:1717], 25 fps, 25 tbr, 25 tbn, 25 tbc
[image2 @ 0x21267a0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Output #0, image2, to 'wing-x03d/frame_%04d.ppm':
  Metadata:
    encoder         : Lavf57.37.101
    Stream #0:0: Video: ppm, rgb24, 600x338 [SAR 42926:42925 DAR 3048:1717], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.46.100 ppm
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> ppm (native))
Press [q] to stop, [?] for help
frame=  218 fps=0.0 q=-0.0 Lsize=N/A time=00:00:08.72 bitrate=N/A speed=10.1x    
video:129526kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

How much do you want to weight the style reconstruction term? Default value: 1e2 for a resolution of 450x350. Increase for a higher resolution. [1e2] 
 > 1e2

Enter the zero-indexed ID of the GPU to use, or -1 for CPU mode (very slow!). [0] 
 > 0

Computing optical flow. This may take a while...
stylizeVideo.sh: line 84: th: command not found

I ended up running 

th artistic_video.lua -style_image 'styles/mountains.jpg' -content_pattern wing-x03d/frame_%04d.ppm -flow_pattern wing-x03d/flow_600:338/backward_[%d]_{%d}.flo -flowWeight_pattern wing-x03d/flow_600:338/reliable_[%d]_{%d}.pgm -num_images 218 -output_image wing.png -number_format %04d -output_folder '/home/zed/wingsuit/render/' -save_iter 0 -gpu 0 -backend clnn

To use the flow files and it seems to be working that way.

**Comment by manuelruder** [comment]
Probably a problem with the path variable: http://unix.stackexchange.com/questions/163120/command-not-found-via-shell-script-but-works-on-terminal
