### ISSUE TITLE
OptFlow performance question

### ISSUE THREAD

**Issue by zepesm** [manuelruder/artistic-videos#15]
First of all - thanks for putting it all together. Really newbie question here - is it normal that OptFlow process takies about 3min for backward/forward/reliable set for one video frame? (i7-2600k)

**Comment by jbgrant01** [comment]
You may want to open your system monitor to see your memory usage. I suspect you are swapping out to your hard drive. On my system with 8 gigs of RAM working on a 640X360 frame uses up to 2.6 gigs of RAM for the OptFlow process. You may need to go down to 450X350 resolution to fit in your machine. On mine the reliable sets run 16 seconds.

**Comment by manuelruder** [comment]
Yes, that's normal. Especially DeepMatching needs a lot of resources. You can regulate DeepMatching by passing the `-R <n>` command line option to DeepMatching in run-deepflow.sh. This option allows you to downsize the input images by a factor 2^n (default: n=1). However, I have sometimes observed that non-default values for this option breaks the reliable set calculation. So have an eye on this if you experiment with that.

On the other side, you can also run the optical flow calculation in parallel, as I stated here: https://github.com/manuelruder/artistic-videos/issues/9 .
