### ISSUE TITLE
Question from a novice

### ISSUE THREAD

**Issue by bododge** [manuelruder/artistic-videos#2]
I get as far as generating the first image using the included  stylizeVideo.sh, however when that image completes I see this error: 
/usr/local/bin/luajit: /usr/local/share/lua/5.1/image/init.lua:346: video_6/frame_0002.ppm: No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/image/init.lua:346: in function 'load'
	./artistic_video_core.lua:557: in function 'getContentImage'
	artistic_video.lua:131: in function 'main'
	artistic_video.lua:340: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010d746c40
admins-Mac-Pro:artistic-videos-master 2 sampsen$ 

I can see that frame_0001.ppm was generated but not frame_0002.ppm I also have an empty folder for flow_400x300 and a single out-1.png file generated. 

Does this indicate an issue with my deepflow utility? I am daring to try this from OSX 10.10.5...

Other ideas are greatly appreciated. Thanks

**Comment by manuelruder** [comment]
No, this indicated an issue with ffmpeg. What happens if you just call `ffmpeg -i <your_video> frame_%04d.ppm`?

**Comment by bododge** [comment]
I appreciate the reply, you were right ffmpeg wasn't completing the extraction because I was pointing it at the already extracted first frame(s) instead of the .mp4 file..However now I am not having any luck getting the optical flow working. I wish there was some hearty examples of how to set that up to give us noobs a chance of making this thing work! Awesome work though, just wish I could get it going.

**Comment by manuelruder** [comment]
You are right, we could have provided an example script. I have already included one in my last commit. The lines from your error message refer exactly to the positions where the optical flow utility is called. Could you maybe just update your local copy of this repository, and then use the updated scripts, as explained in the description?

**Comment by bododge** [comment]
I downloaded and tried, but I can't run the static binary versions since I'm on a mac. I know that's not really your problem, however I'm trying and trying to get these deepflow and deepmatching to compile and I run into a slew of errors. Any idea what's causing them? If not, I'll keep working on it on my own.  Thanks

./std.h:68:11: error: expected unqualified-id
const int INT_MIN = (0x80000000);
          ^
/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/include/limits.h:67:20: note: expanded from macro 'INT_MIN'
#define INT_MIN   (-__INT_MAX__  -1)
                   ^
In file included from conv.cpp:18:
./std.h:68:11: error: expected ')'
/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/include/limits.h:67:20: note: expanded from macro 'INT_MIN'
#define INT_MIN   (-__INT_MAX__  -1)
                   ^
./std.h:68:11: note: to match this '('
/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/include/limits.h:67:19: note: expanded from macro 'INT_MIN'
#define INT_MIN   (-__INT_MAX__  -1)
                  ^
In file included from conv.cpp:18:
./std.h:69:11: error: expected unqualified-id
const int INT_MAX = 0x7FFFFFFF;
          ^
/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/include/limits.h:62:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^
<built-in>:61:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^
conv.cpp:19:10: fatal error: 'omp.h' file not found
#include "omp.h"

**Comment by manuelruder** [comment]
No, I can't help you with that.

**Comment by ibaaj** [comment]
use [clang-omp](https://clang-omp.github.io)
