### ISSUE TITLE
license

### ISSUE THREAD

**Issue by RomanKuskowski** [manuelruder/artistic-videos#20]
Hello,
Iam working as a video designer in the theater and would love to use 2-4 minutes of artistic-videos in a 90 minutes play. Of course i would citate your amazing work in every way possible and not take the credit for it. It would just fit in so good in the context of the play. Do you see any chance that this would be possible ?

**Comment by manuelruder** [comment]
For licensing issues, please email me. Mail address can be found in my paper.
