### ISSUE TITLE
Time to process in multipass

### ISSUE THREAD

**Issue by jbgrant01** [manuelruder/artistic-videos#23]
I have a 10 second clip with 285 frames. It looks like it is taking 85 seconds per frame in the first five passes. At that rate it looks to take a little over 4 days to render for 15 passes. I was wondering if it will speed up in later passes if the total losses start to decrease?

**Comment by manuelruder** [comment]
Yes, the mutipass version is slower than the singlepass version of the algorithm. The number of iterations per pass does not decrease, but probably you don't need 15 passes until the result starts looking good. This is just the number you need until the algorithm to converge. You could also try to initialize with the content image. This should decrease the number of passes you'll need even further, but the result may loose a little bit of diversity.
