### ISSUE TITLE
How to do real time processing

### ISSUE THREAD

**Issue by sukerlove** [manuelruder/artistic-videos#25]
Dear manuelruder:

```
I use ./stylizeVideo.sh  ./ball.mp4  ./example/seated-nude.jpg
```

ball.mp4:720p with 25 fps 18 seconds video
and I process dst 640x480 stylevideo
It took 5 hours to complete.

Machine configuration:
OS............: ubuntu14.04
Memory........: 32G
CPU...........: Intel Core i7-6700K 4.00GHz*8
DisplayCard...: NVIDIA GeForce GTX 1080
Harddisk......: 256G ssd

---

gtx1080@suker:~$ nvidia-smi 
Tue Aug 23 21:17:24 2016  
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.35                 Driver Version: 367.35                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
| 34%   35C    P8    10W / 200W |   1306MiB /  8112MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1169    G   /usr/bin/X                                    1014MiB |
|    0      2025    G   compiz                                          59MiB |
|    0      3571    G   unity-control-center                             2MiB |
|    0     10412    G   ...ves-passed-by-fd --v8-snapshot-passed-by-   227MiB |
+-----------------------------------------------------------------------------+
gtx1080@suker:~$ 

I am looking forward to your reply.
Thanks

**Comment by manuelruder** [comment]
Real-time is not possible with my application.

**Comment by sukerlove** [comment]
thanks for reply:
how to quickly for process a video

ball.mp4:720p with 25 fps 18 seconds video
and I process dst 640x480 stylevideo
It took 5 hours to complete.

thanks
