### ISSUE TITLE
Distribution in a compute cluster

### ISSUE THREAD

**Issue by flv0** [manuelruder/artistic-videos#27]
Hello, and thanks for this inspiring work! I wonder if it's possible to split/distribute the work between a number of cluster nodes. For the frame-to-frame optical flow estimation it seems no problem, however the styling algorithm takes into account the predecessor result frame as far as I can tell. Have you thought about this, and do you see a way to split the computation while maintaining global temporal consistency, maybe with some amount of communication between the nodes at runtime?

**Comment by manuelruder** [comment]
No, I haven't any plans to implement such a feature. But for longer movies, there will probably be multiple scenes which can be processed independently from each other. If you are planning to use our software for a commercial movie, please also keep [out license](https://github.com/manuelruder/artistic-videos/blob/master/LICENSE) in mind.

**Comment by flv0** [comment]
Ok, thank you! This is for personal use and not a movie production. But now that you mention it, I would like to get a clarification regarding the license. I'm doing digital arts and VJing. I do not plan to sell the rendered video material at all, but would like to use some of it as part of a composition for live performance or a projection mapping installation. I will probably not get paid for doing it, so I would definitely consider it 'non-profit' use. Would that be in accordance with the license as you intended it?

**Comment by manuelruder** [comment]
Well, that depends on where the video material is shown in the end. If you want to show your composition in a club / on a stage, where people have to pay for it, I would consider this as a commercial usage. Even if you (personally) do this for non-profit, if someone else directly or indirectly generates income using my technique, this counts as commercial usage. Please email me if you need further clarification or if your employer needs a permission for commercial usage.

**Comment by flv0** [comment]
Ok, thank you for the information! Closing the issue.
