### ISSUE TITLE
DeepMatching dependency - GPU version

### ISSUE THREAD

**Issue by filmo** [manuelruder/artistic-videos#35]
I've been able to use the deepmatching-static binary.

However, I've having a heck of time trying to compile [the GPU](http://lear.inrialpes.fr/src/deepmatching/) version of deepmatch.

Has anybody been able to successfully compile this on ubuntu? It seems like the code from 2015 doesn't match current installs of caffe and the documentation on google tools is thin as to what's expected.

If anybody has had any luck getting this compiled, please let me know. Specifically I'm having a hard time understanding what google tools are required and where they are expected to be installed on Ubuntu.

**Comment by ChoclateRain** [comment]
@filmo  Did you end up getting the gpu version to compile? or finding an already compiled one perhaps? i know the caffe version that its setup to use is ancient but youll have to use that version
Im trying to find a docker with it already setup (that'd be amazing)

**Comment by filmo** [comment]
See https://github.com/manuelruder/artistic-videos/issues/41#issuecomment-277069291
