### ISSUE TITLE
deepmatching-static segfaults on ubuntu 16.04 

### ISSUE THREAD

**Issue by Teepareep** [manuelruder/artistic-videos#38]
Hello,

I migrated my setup to a fresh machine and am running into a strange issue with deepmatching segfaulting shortly after running (10 minutes?). 

Ubuntu 16.04
Linux mlart 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
GTX Titan X (Maxwell)
CPU: Intel(R) Core(TM) i7-5775C CPU @ 3.30GHz

I installed systemd-coredump and it spins up a bunch of processes as soon as deepmatching-static starts. Here's an example coredump. I'm not very familiar with debugging these, so sorry for the noob question here. 

> $ coredumpctl info 8618
>            PID: 8618 (deepmatching-st)
>            UID: 0 (root)
>            GID: 0 (root)
>         Signal: 11 (SEGV)
>      Timestamp: Tue 2017-01-17 12:16:17 PST (30min ago)
>   Command Line: ./deepmatching-static /content/vid/example/frames/frame_0004.ppm /content/vid/example/frames/frame_0005.ppm -nt 0
>     Executable: /root/artistic-videos/deepmatching-static
>  Control Group: /docker/922e2593770bb0190376fdae5482d60ff373a0aa32565f3d84e33b482e1a0c3b
>          Slice: -.slice
>        Boot ID: 156c400d834845b2a36f1e00da8dcf63
>     Machine ID: 57adaac235924da8aeaa7dd1b3a478e9
>       Hostname: mlart
>       Coredump: /var/lib/systemd/coredump/core.deepmatching-st.0.156c400d834845b2a36f1e00da8dcf63.8618.1484684177000000000000.xz
>        Message: Process 8618 (deepmatching-st) of user 0 dumped core.
> 
>                 Stack trace of thread 329:
>                 #0  0x0000000000457bb0 n/a (/var/lib/docker/aufs/diff/f9fada9ab7f83d8797c8b483087cce5fdfb9f61eabe3e9a8f5fa4649103e7989/root/artistic-videos/deepmatching-static)

I'm running this with nvidia-docker, which was working great on my previous machine. I thought I'd ping this repo about possible solutions before I go ordering more RAM and start swapping hardware.

**Comment by Teepareep** [comment]
Extremely strange but when I do the quarter-res optical flow calculations mentioned 
[in issue 34](https://github.com/manuelruder/artistic-videos/issues/34) I no longer seem to be having this issue. Going to test further.

**Comment by manuelruder** [comment]
Deepmatching is very memory intensive. quarter-res reduces memory consumption of course. If your video has a high resolution, I don't see a reason why not just stick with quarter-res.

**Comment by Teepareep** [comment]
I think this is just a hardware issue. Closing for now.
