### ISSUE TITLE
Please open makeOptFlow.sh and specify the command line for computing the optical flow.

### ISSUE THREAD

**Issue by Sugarbank** [manuelruder/artistic-videos#4]
HI could you give an example of how to specify this in the script if i'm using deepflow?

Thanks

**Comment by manuelruder** [comment]
I would recommend to create an auxiliary script `run-deepflow.sh <file1> <file2> <output>`. There you can write something like this:

`<deepmatching_path>/deepmatching-static $1 $2 | <deepflow_path>/deepflow2-static $1 $2 $3 -match`

(If you don't want to or can't use the static builds, then you have to remove the `-static` suffix of course.)

**Comment by djebm2** [comment]
@manuelruder @Sugarbank you can add `-nt 0` to `deepmatching-static $1 $2` to enable multithreading.  By the way, is there a GPU version for DeepFlow ?

**Comment by manuelruder** [comment]
There is no GPU version of DeepFlow.
If you want to speedup the process, you could compute the optical flow in parallel to the torch script. Then it's anyway beneficial to run it on CPU, because the torch script mainly runs on GPU.
Just call ".\makeOptFlow.sh ..." in a different process than "th artistic_video.sh ...".

**Comment by Sugarbank** [comment]
Hi,Sorry this is a bit newbie but...Where do I set the path to the optical flow utilities in the makeOptFlow.sh file?
it say "# Specify the path to the optical flow utility here."
Sorry for the stupid questions.









Date: Fri, 6 May 2016 09:19:27 -0700

**Comment by manuelruder** [comment]
@Sugarbank if you use the newest version of this script there is nothing you have to change here. Just download and place deepflow and deepmatching in the same directory as the scripts, as said in the updated readme. In case you want to use your own algorithm, check out line 3 where it says `flowCommandLine="..."`.
